#!/bin/bash 

# 注意：
# 这里生产出来的 ext2 image file 需要内核打开 RamDisk 支持同时
# Device Driver
# ----->Block Device
# ------->Default Ram Disk Size（kbytes）
# 的值改为32768就好了否则引导内核的时候会报告
# RAMDISK: incomplete write (6267 != 32768）
# write error 
# 进而照不到内存rootfs. 如果不能很容易调整这个参数那么需要使用
# new-image-cpio
# TODO: 把kernel 的 src.rpm 中修改参数，然后从新编译.

inst_dir="/usr/local/jumpstart/images/inst"

if [ ! -e $inst_dir ];  then
  echo Directory $inst_dir does not exist, can not run this script
  exit
fi


cd $inst_dir

if [[ $# > 1 ]]; then
    if [[ $1 == "-f" ]]; then FORCE=1; shift; fi
fi

NAME=$1
NAME=`echo $1 | sed 's#/$##'`

if [ "x$NAME" == "x" ]; then
  echo Please specify what image to build
  exit
fi

if [ ! -d $NAME ];  then
  echo Directory $1 does not exist, can not create image
  exit
fi

DIR=`pwd`
echo Processing dir $NAME 

mkdir -p $DIR/disk.mnt
umount $DIR/disk.mnt

if [[ ! -f disk.img || $FORCE == 1 ]]; then 
    dd if=/dev/zero of=disk.img bs=1000k count=128
    mke2fs -F disk.img
fi
mount -o loop -t ext2 $DIR/disk.img $DIR/disk.mnt || exit 1

rsync -H -a $1/. disk.mnt/.
rsync -H -a -v RS-installer/ disk.mnt/.
echo Ramdisk image generated `date`  >>disk.mnt/etc/motd
echo from `hostname`:$DIR >>disk.mnt/etc/motd

umount $DIR/disk.mnt
gzip -9 -cv disk.img > /usr/local/jumpstart/out/tftpboot/$NAME.gz
#mount -o loop -t ext2 $DIR/disk.img $DIR/disk.mnt

#mv disk.gz /tftpboot/${NAME}.gz
#rmdir disk.mnt
